<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
	public function save($categoria)
    {   
        $em = $this->getEntityManager();
        $em->persist($categoria);
        $em->flush();
    }


    public function delete($categoria)
    {   
        $em = $this->getEntityManager();
        $em->remove($em->merge($categoria));
        $em->flush();
    }

    public function update($categoria)
    {   
        $em = $this->getEntityManager();
        $em->persist($em->merge($categoria));
        $em->flush();
    }
}
