<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MixRepository extends EntityRepository
{
	
	public function save($mix)
	{
		$em = $this->getEntityManager();
		$em->persist($mix);
		$em->flush();
		return $mix;
	}
}
