<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PaqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteRepository extends EntityRepository
{
	public function findDisponiblesBy(Presentacion $presentacion)
	{
		$em = $this->getEntityManager();
		$result = $em->createQuery("SELECT COUNT(l.id) FROM BGRSerranoProductoBundle:Paquete l
            WHERE l.presentacion = :presentacion  AND l.estado =  'DISPONIBLE'"
		)->setParameter('presentacion', $presentacion->getId())->getSingleScalarResult();
	
		return $result;
	}

	public function fraccionar($paqueteId)
   {    	 
    	$em = $this->getEntityManager();
      $p = $em->getRepository('BGRSerranoProductoBundle:Paquete')->find($paqueteId);
    	$p->setEstado('FRACCIONADO');
    	$em->persist($p);
    	$conection = $em->getConnection();
     	$em->flush();
     	return $p;
   }

   
   public function validarPaqueteProducto($paqueteId, $productoId)
   {
   	$em = $this->getEntityManager();

   	$paquete=$em->getRepository('BGRSerranoProductoBundle:Paquete')->find($paqueteId);
   	if($paquete ==null || $paquete->getEstado() != "DISPONIBLE"){
   		return false;
   	}
   	
   	$presentacion= $em->getRepository('BGRSerranoProductoBundle:Presentacion')->find($paquete->getPresentacion()->getId());
  
   	return $presentacion->getProducto()->getId() == $productoId;
   }
   
   
}
