<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PresentacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentacionRepository extends EntityRepository
{
    public function save($presentacion)
    {   
        $em = $this->getEntityManager();
	    $presentacion->setProducto($em->merge($presentacion->getProducto()));
	    $presentacion->setLote($em->merge($presentacion->getLote()));
	    $presentacion->setMaterial($em->merge($presentacion->getMaterial()));
	    $presentacion->setUnidad_de_medida($em->merge($presentacion->getUnidad_de_medida()));
        $em->persist($presentacion);
        $em->flush();
    }

    public function update($presentacion)
    {   
        $em = $this->getEntityManager();
        $presentacion->setProducto($em->merge($presentacion->getProducto()));
        $presentacion->setLote($em->merge($presentacion->getLote()));
        $presentacion->setMaterial($em->merge($presentacion->getMaterial()));
        $presentacion->setUnidad_de_medida($em->merge($presentacion->getUnidad_de_medida()));
        $em->persist($em->merge($presentacion));
        $em->flush();
    }

}
