<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ProductoUnidadDeMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoUnidadDeMedidaRepository extends EntityRepository
{
	public function save($productoUnidadDeMedida)
    {   
        $em = $this->getEntityManager();
        $em->persist($productoUnidadDeMedida);
        $em->flush();
    }


    public function delete($productoUnidadDeMedida)
    {   
        $em = $this->getEntityManager();
        $em->remove($em->merge($productoUnidadDeMedida));
        $em->flush();
    }

    public function update($productoUnidadDeMedida)
    {   
        $em = $this->getEntityManager();
        $em->persist($em->merge($productoUnidadDeMedida));
        $em->flush();
    }
}
