<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{

	public function save(Producto $producto)
    {   
        $em = $this->getEntityManager();
	    $producto->setCategoria($em->merge($producto->getCategoria()));
	    
	    $umTemporales = new ArrayCollection();
	    $prtemporales = new ArrayCollection();
	     
	    foreach($producto->getUnidadDeMedidas() as $unidadMedida){
				$umTemporales->add($em->merge($unidadMedida));
        }

        foreach($producto->getProveedores() as $proveedor){
        	$prtemporales->add($em->merge($proveedor));
        }
        
        $producto->setUnidadDeMedidas($umTemporales);
        $producto->setProveedores($prtemporales);
        
        $em->persist($producto);
        $em->flush();
    }

	public function update($producto)
    {   
		  //TODO: persistir el manyToMany, por ahora se hace atraves de 
		  // mapear la tabla intermedia.
 		  
 		  $em = $this->getEntityManager();	         
		  $em->persist($em->merge($producto));
        $em->flush();
    }

    public function delete($producto)
    {   
        $em = $this->getEntityManager();
        $em->remove($em->merge($producto));
        $em->flush();
    }
    public function findByCategoria($categoria)
    {
        $em = $this->getEntityManager();
        $result = $em->createQuery("SELECT l FROM BGRSerranoProductoBundle:Producto l   
            WHERE l.categoria = :categoria"
        )->setParameter('categoria', $categoria->getId())->getArrayResult();
    
        return $result;
    }
    

}
