<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends EntityRepository
{
	public function findByProductoId($producto_id)
	{
	
		$em = $this->getEntityManager();
	
		$rsm = new ResultSetMapping();
			
	
		$rsm->addScalarResult('id', 'id');
		$rsm->addScalarResult('name', 'name');	
	
		$query = $em->createNativeQuery("
			  SELECT   pr.*
	          FROM Proveedor pr
	          JOIN producto_proveedor pp ON ( pp.proveedor_id = pr.id )
			  WHERE  pp.producto_id = ?",$rsm)->setParameter(1,$producto_id);
	
		$result = $query->getResult();
		return $result;
	}
}
