<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemanenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemanenteRepository extends EntityRepository
{
	public function save($remanente)
    {   
        $em = $this->getEntityManager();
        $em->persist($em->merge($remanente));
        $em->flush();
    }
}
