<?php

namespace BGR\Serrano\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UnidadDeMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadDeMedidaRepository extends EntityRepository
{
	public function save($unidadMedida)
    {   
        $em = $this->getEntityManager();
        $em->persist($unidadMedida);
        $em->flush();
    }


    public function delete($unidadMedida)
    {   
        $em = $this->getEntityManager();
        $em->remove($em->merge($unidadMedida));
        $em->flush();
    }

    public function update($unidadMedida)
    {   
        $em = $this->getEntityManager();
        $em->persist($em->merge($unidadMedida));
        $em->flush();
    }
}
